In [2]:
# import numpy, pandas, matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

import torch


$$ (2a + 3b)^2 $$

In [ ]:
# plain vanilla Python
a, b = 15, 20
(2 * a + 3 * b) ** 2
# 8100

8100

In [ ]:
# numpy arrays
a, b = np.array([15]), np.array([20])
(2 * a + 3 * b) ** 2
# array([8100.])

array([8100])

In [ ]:
# TensorFlow
a, b = tf.constant(15), tf.constant(20)
(2 * a + 3 * b) ** 2
# tf.Tensor: shape=(), dtype=int32, numpy=8100

<tf.Tensor: shape=(), dtype=int32, numpy=8100>

In [ ]:
# PyTorch
a, b = torch.tensor(15), torch.tensor(20)
(2 * a + 3 * b) ** 2
# tensor(8100)

tensor(8100)

In [4]:
my_nums = np.arange(0, 10, 2)
my_nums
#

array([0, 2, 4, 6, 8])

In [5]:
my_nums.max()
#

8

In [6]:
my_nums.argmax()
#

4