In [1]:
# %pip install tensorflow
# %pip install torch torchvision

In [2]:
# import numpy, pandas, matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

import keras

import torch


$$ (2a + 3b)^2 $$

In [3]:
# plain vanilla Python
a, b = 15, 20
(2 * a + 3 * b) ** 2
# 8100

8100

In [4]:
# numpy arrays
a, b = np.array([15]), np.array([20])
(2 * a + 3 * b) ** 2
# array([8100.])

array([8100])

In [12]:
# TensorFlow
a, b = tf.constant(15), tf.constant(20)
(2 * a + 3 * b) ** 2
# tf.Tensor: shape=(), dtype=int32, numpy=8100

<tf.Tensor: shape=(), dtype=int32, numpy=8100>

In [6]:
# PyTorch
a, b = torch.tensor(15), torch.tensor(20)
(2 * a + 3 * b) ** 2
# tensor(8100)

tensor(8100)

In [11]:
a.shape

torch.Size([])

In [7]:
my_nums = np.arange(0, 10, 2)
my_nums
#

array([0, 2, 4, 6, 8])

In [8]:
my_nums.max()
#

np.int64(8)

In [9]:
my_nums.argmax()
#

np.int64(4)

In [14]:
a = np.array([3,4,5])
b = np.array([7, 8, 20])

result = (2*a + 3*b)**2
result

array([ 729, 1024, 4900])

In [15]:
a = torch.tensor([3,4,5])
b = torch.tensor([7, 8, 20])

result = (2*a + 3*b)**2
result

tensor([ 729, 1024, 4900])

In [16]:
result.shape

torch.Size([3])

In [17]:
result.requires_grad

False

In [18]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
x = torch.zeros(10)
y = torch.zeros(5)

weights = torch.randn(10, 5, requires_grad=True)

In [20]:
weights

tensor([[ 1.7813,  0.6694, -1.8649,  1.6095,  0.2529],
        [ 0.6971,  0.5715, -0.3103,  0.3620, -1.3626],
        [ 0.7402,  0.7831, -0.6569, -1.9201, -0.4609],
        [-1.4335,  1.0841, -0.2741, -0.9674, -0.6235],
        [ 0.5283,  2.6784, -0.3507, -0.0503,  0.0754],
        [ 1.7009,  1.1456, -1.5223,  0.4045, -1.2876],
        [ 0.5936, -0.0087,  0.6794, -0.5985,  1.2271],
        [-1.2506, -0.4022,  1.2158,  2.2485, -0.3393],
        [ 1.1806,  0.9601,  1.6735,  0.7100,  0.7833],
        [ 1.4520, -1.6663, -0.8094,  0.2709,  0.0540]], requires_grad=True)

In [21]:
weights.shape

torch.Size([10, 5])

In [23]:
x.shape

torch.Size([10])

In [25]:
weights = torch.randn(10, 5, requires_grad=True)
intercept = torch.randn(5, requires_grad=True)

activation = torch.matmul(x, weights) + intercept

In [26]:
activation

tensor([-0.4295, -1.0758, -0.4934, -0.0229,  2.2363], grad_fn=<AddBackward0>)

In [28]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(activation, y)

In [29]:
loss

tensor(0.8582, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [ ]:
loss.backward()

In [31]:
loss

tensor(0.8582, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [32]:
weights.grad

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [33]:
intercept.grad

tensor([0.0788, 0.0509, 0.0758, 0.0989, 0.1807])